/**
 * FirstSessionPage
 * First Session - $100M Mind Insurance Feature
 *
 * Post-onboarding experience that:
 * 1. Shows instant MIO welcome message
 * 2. Displays analyzing animation while protocol generates
 * 3. Reveals pattern name and first protocol
 * 4. Engages user with first MIO question
 * 5. Navigates to Coverage Center
 */

import React, { useEffect, useState, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Loader2 } from 'lucide-react';
import { cn } from '@/lib/utils';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';

// First Session components
import {
  MIOWelcomeMessage,
  AnalyzingAnimation,
  ProtocolRevealCard,
  FirstEngagementQuestion,
  EngagementConfirmation,
} from '@/components/first-session';

// Services
import { getActiveInsightProtocol } from '@/services/mioInsightProtocolService';

// Types
import type { MIOInsightProtocolWithProgress } from '@/types/protocol';

// ============================================================================
// TYPES
// ============================================================================

type SessionStage =
  | 'welcome'       // Instant MIO welcome
  | 'analyzing'     // Protocol generation animation
  | 'reveal'        // Pattern + protocol reveal
  | 'engagement'    // First question
  | 'confirmation'  // Thank you + CTA
  | 'error';        // Error state

// ============================================================================
// COMPONENT
// ============================================================================

export default function FirstSessionPage() {
  const navigate = useNavigate();
  const { user, loading: authLoading } = useAuth();
  const { toast } = useToast();

  // State
  const [stage, setStage] = useState<SessionStage>('welcome');
  const [protocol, setProtocol] = useState<MIOInsightProtocolWithProgress | null>(null);
  const [isAnalysisComplete, setIsAnalysisComplete] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // User name for personalization
  const userName = user?.user_metadata?.first_name || user?.user_metadata?.full_name?.split(' ')[0] || '';

  // ============================================================================
  // DATA FETCHING
  // ============================================================================

  /**
   * Fetch the user's protocol (generated by N8n webhook after assessment)
   * Poll until available or timeout
   */
  const fetchProtocol = useCallback(async () => {
    if (!user?.id) return;

    const maxAttempts = 15; // ~30 seconds total
    const pollInterval = 2000; // 2 seconds

    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      try {
        const activeProtocol = await getActiveInsightProtocol(user.id);

        if (activeProtocol) {
          setProtocol(activeProtocol);
          setIsAnalysisComplete(true);
          return;
        }

        // Wait before next attempt
        await new Promise((resolve) => setTimeout(resolve, pollInterval));
      } catch (err) {
        console.error('[FirstSessionPage] Error fetching protocol:', err);
        // Continue polling unless it's a critical error
      }
    }

    // Timeout - no protocol found
    console.error('[FirstSessionPage] Protocol fetch timeout');
    setError("We're taking longer than expected. Please wait a moment...");

    // Continue polling in background
    const backgroundPoll = setInterval(async () => {
      try {
        const activeProtocol = await getActiveInsightProtocol(user.id);
        if (activeProtocol) {
          setProtocol(activeProtocol);
          setIsAnalysisComplete(true);
          setError(null);
          clearInterval(backgroundPoll);
        }
      } catch (err) {
        // Silent continue
      }
    }, 5000);

    // Cleanup after 2 minutes
    setTimeout(() => {
      clearInterval(backgroundPoll);
      if (!protocol) {
        setStage('error');
        setError('Protocol generation is taking longer than expected. Please try refreshing.');
      }
    }, 120000);
  }, [user?.id, protocol]);

  // ============================================================================
  // EFFECTS
  // ============================================================================

  // Start fetching protocol when page loads
  useEffect(() => {
    if (user?.id && !authLoading) {
      fetchProtocol();
    }
  }, [user?.id, authLoading, fetchProtocol]);

  // Transition from welcome to analyzing after delay
  useEffect(() => {
    if (stage === 'welcome') {
      const timer = setTimeout(() => {
        setStage('analyzing');
      }, 3000);
      return () => clearTimeout(timer);
    }
  }, [stage]);

  // Transition from analyzing to reveal when protocol is ready
  useEffect(() => {
    if (stage === 'analyzing' && isAnalysisComplete && protocol) {
      setStage('reveal');
    }
  }, [stage, isAnalysisComplete, protocol]);

  // ============================================================================
  // HANDLERS
  // ============================================================================

  const handleAnalysisComplete = useCallback(() => {
    if (protocol) {
      setStage('reveal');
    }
  }, [protocol]);

  const handleRevealComplete = useCallback(() => {
    setStage('engagement');
  }, []);

  const handleEngagementSubmit = useCallback(async (response: string) => {
    setIsSubmitting(true);

    try {
      // TODO: Save engagement response to database via service
      // For now, just transition to confirmation
      console.log('[FirstSessionPage] Engagement response:', response);

      // Simulate API call
      await new Promise((resolve) => setTimeout(resolve, 1000));

      setStage('confirmation');
    } catch (err) {
      console.error('[FirstSessionPage] Error saving engagement:', err);
      toast({
        title: 'Error',
        description: 'Failed to save your response. Please try again.',
        variant: 'destructive',
      });
    } finally {
      setIsSubmitting(false);
    }
  }, [toast]);

  const handleEngagementSkip = useCallback(() => {
    setStage('confirmation');
  }, []);

  const handleViewCoverage = useCallback(() => {
    navigate('/mind-insurance/coverage');
  }, [navigate]);

  const handleRetry = useCallback(() => {
    setError(null);
    setStage('analyzing');
    fetchProtocol();
  }, [fetchProtocol]);

  // ============================================================================
  // RENDER
  // ============================================================================

  // Loading state
  if (authLoading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-purple-500" />
      </div>
    );
  }

  // Not authenticated
  if (!user) {
    return (
      <div className="min-h-screen bg-background flex flex-col items-center justify-center p-4">
        <p className="text-muted-foreground">Please sign in to continue.</p>
        <Button onClick={() => navigate('/auth')} className="mt-4">
          Sign In
        </Button>
      </div>
    );
  }

  // Error state
  if (stage === 'error') {
    return (
      <div className="min-h-screen bg-background">
        <div className="container max-w-2xl mx-auto px-4 py-8">
          <div className="text-center space-y-4">
            <h2 className="text-2xl font-bold text-foreground">
              Something went wrong
            </h2>
            <p className="text-muted-foreground">
              {error || 'We encountered an issue generating your protocol.'}
            </p>
            <div className="flex gap-3 justify-center">
              <Button onClick={handleRetry} variant="default">
                Try Again
              </Button>
              <Button
                onClick={() => navigate('/mind-insurance')}
                variant="outline"
              >
                Go to Mind Insurance
              </Button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-purple-50/30 dark:to-purple-950/10">
      <div className="container max-w-2xl mx-auto px-4 py-8">
        {/* Back button - only show after reveal */}
        {(stage === 'engagement' || stage === 'confirmation') && (
          <Button
            variant="ghost"
            onClick={() => navigate('/mind-insurance')}
            className="mb-6 -ml-2"
          >
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back
          </Button>
        )}

        {/* Content area */}
        <div className="space-y-6">
          {/* Stage: Welcome */}
          {stage === 'welcome' && (
            <MIOWelcomeMessage userName={userName} isVisible={true} />
          )}

          {/* Stage: Analyzing */}
          {stage === 'analyzing' && (
            <div className="space-y-6">
              <MIOWelcomeMessage userName={userName} isVisible={true} />
              <AnalyzingAnimation
                isAnalyzing={!isAnalysisComplete}
                onComplete={handleAnalysisComplete}
                minDuration={8000}
              />
              {error && (
                <p className="text-sm text-amber-600 dark:text-amber-400 text-center">
                  {error}
                </p>
              )}
            </div>
          )}

          {/* Stage: Reveal */}
          {stage === 'reveal' && protocol && (
            <div className="space-y-6">
              <ProtocolRevealCard
                protocol={{
                  id: protocol.id,
                  title: protocol.title,
                  pattern_name: protocol.pattern_targeted || 'Your Pattern',
                  pattern_description: protocol.description,
                  day_count: protocol.total_days,
                  mio_intro_message: protocol.mio_intro,
                  first_day_preview: protocol.days?.[0]?.title,
                }}
                isRevealing={true}
                onViewProtocol={handleRevealComplete}
              />
            </div>
          )}

          {/* Stage: Engagement */}
          {stage === 'engagement' && protocol && (
            <div className="space-y-6">
              <FirstEngagementQuestion
                patternName={protocol.pattern_targeted}
                protocolTitle={protocol.title}
                onSubmit={handleEngagementSubmit}
                onSkip={handleEngagementSkip}
                isSubmitting={isSubmitting}
                isVisible={true}
              />
            </div>
          )}

          {/* Stage: Confirmation */}
          {stage === 'confirmation' && (
            <EngagementConfirmation
              userName={userName}
              onContinue={handleViewCoverage}
            />
          )}
        </div>
      </div>
    </div>
  );
}
